// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface GetAllTodosRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.GetAllTodosRequestMessage)
    com.google.protobuf.MessageOrBuilder {
}
