// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface GetAllTodosResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.GetAllTodosResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   */
  int getStatus();

  /**
   * <code>repeated string todos = 2;</code>
   */
  java.util.List<java.lang.String>
      getTodosList();
  /**
   * <code>repeated string todos = 2;</code>
   */
  int getTodosCount();
  /**
   * <code>repeated string todos = 2;</code>
   */
  java.lang.String getTodos(int index);
  /**
   * <code>repeated string todos = 2;</code>
   */
  com.google.protobuf.ByteString
      getTodosBytes(int index);

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
