// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface GetTodoRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.GetTodoRequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 index = 1;</code>
   */
  int getIndex();
}
